### ISSUE TITLE
ImportError: cannot import name 'secretmanager' from 'google.cloud' (unknown location)

### ISSUE THREAD

**Issue by RJV2083** [googleapis/python-secret-manager#319]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-secret-manager/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version:
  - Python version: `python --version`
  - pip version: `pip --version`
  - `google-cloud-secret-manager` version: `pip show google-cloud-secret-manager`

#### Steps to reproduce

  1. ?
  2. ?

#### Code example

```python
# example
```

#### Stack trace
```
# example
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by parthea** [comment]
Hi @RJV2083 ,

I'm not able to reproduce the error. Please could you ensure that the environment where you installed the `google-cloud-secret-manager` client is the same environment where you experienced the error.

**Comment by ianyoung** [comment]
I'm also experiencing this issue.

**Environment details**

- OS type and version: Cloud Function gen1
- Python version: 3.10
- google-cloud-secret-manager version: google-cloud-secret-manager==2.12.3

I'm using Pipenv locally to build my Cloud Function. I know that `Pipfile` and `Pipfile.lock` isn't supported. However I'm deploying my Cloud Function using GitHub Actions. As part of the build process I generate a `requirements.txt` file using Pipenv:

![ghactions-deploy](https://user-images.githubusercontent.com/66717/185421849-33353678-0f48-4a1a-84d4-1e6f2864354f.png)

The output of the requirements.txt file is:

```
-i https://pypi.org/simple
cachetools==5.2.0
certifi==2022.6.15
charset-normalizer==2.1.0
click==8.1.3
cloudevents==1.5.0
deprecation==2.1.0
flask==2.2.2
functions-framework==3.2.0
google-api-core[grpc]==2.8.2
google-auth==2.10.0
google-cloud-secret-manager==2.12.3
googleapis-common-protos==1.56.4
grpc-google-iam-v1==0.12.4
grpcio==1.47.0
grpcio-status==1.47.0
gunicorn==20.1.0
idna==3.3
itsdangerous==2.1.2
jinja2==3.1.2
markupsafe==2.1.1
packaging==21.3
proto-plus==1.22.0
protobuf==4.21.5
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==3.0.9
requests==2.28.1
rsa==4.9
setuptools==65.1.0
six==1.16.0
urllib3==1.26.11
watchdog==2.1.9
werkzeug==2.2.2
```

However, the deployment step in the build process fails with the message:

> Error: google-github-actions/deploy-cloud-functions failed with: operation failed: Function failed on loading user code. This is likely due to a bug in the user code.

The logs and the Cloud Function dashboard indicate the exact error:

<img width="686" alt="cf-error" src="https://user-images.githubusercontent.com/66717/185422652-c8fbebce-d014-4b06-9763-788a418ca36d.png">

Which points to my import line:

`from google.cloud import secretmanager`

I'm not entirely sure if this is an error with the import or if it's because the `requirements.txt` file is not copied across as part fo the build process? When I view the source code of the Cloud Function I don't see the `requirements.txt` file. Should I be seeing it in this view? Should this step in the build process not copy it across?

```
steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      
      # To later run commands to install Pipenv & generate requirements.txt
      # we need to have Python setup in the environment.
      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: pip install pipenv
      - run: pipenv requirements > requirements.txt # Generate requirements.txt file
      - run: pip uninstall --yes pipenv 

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/667423895114/locations/global/workloadIdentityPools/gh-pool3/providers/gh-provider3"
          service_account: "github-actions-sa@cloud-function-test-359314.iam.gserviceaccount.com"

      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v0"
        with:
          name: "hello"
          description: 'A simple test function'
          runtime: "python310"
          entry_point: "hello_world"
          memory_mb: 256
          source_dir: app
          timeout: 240
          region: "europe-west2"
          https_trigger_security_level: "secure_always"
```

Thanks.
