### ISSUE TITLE
Throwing exception in CI/CD build environment because no default credentials

### ISSUE THREAD

**Issue by steve-kidreads-app** [googleapis/python-secret-manager#82]
#### Environment details

  - OS type and version: Linux (build running as a GitHub Action)
  - Python version: 3.*

#### Steps to reproduce

  1. Write python that attempts to call `secretmanager.SecretManagerServiceClient()`
  2. Try to have GitHub build it as part of a GitHub action

#### The Problem: CI/CD builds on GitHub fail because GitHub doesn't have cloud credentials

I'm trying to have GitHub do automatic python "builds" before I deploy to cloud.  This [Google blog post](https://cloud.google.com/blog/products/identity-security/improving-your-security-posture-with-centralized-secrets-management) by @sethvargo seems to indicate that it's possible to have a GitHub build access your secrets from a GitHub Action, but the explanation seems incomplete and I found no other documentation.  Perhaps more fundamentally, I'm not sure why a "build" of this sort should require access to secrets or cloud credentials, but per the error below `SecretManagerServiceClient()` seems to expect to have default credentials (by way of the main [auth package](https://googleapis.dev/python/google-auth/latest/reference/google.auth.credentials.html#google.auth.credentials.Credentials)).  That seems to make CI/CD hard or impossible.  Is this intended behavior?

```
...in <module> 
secrets = secretmanager.SecretManagerServiceClient()
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/google/cloud/secretmanager_v1/services/secret_manager_service/client.py", line 375, in __init__
    client_info=client_info,
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/google/cloud/secretmanager_v1/services/secret_manager_service/transports/grpc.py", line 170, in __init__
    scopes=self.AUTH_SCOPES, quota_project_id=quota_project_id
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/google/auth/_default.py", line 470, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
```

**Comment by steve-kidreads-app** [comment]
This seems like a similar issue for python-datastore: https://github.com/googleapis/python-datastore/issues/11

**Comment by sethvargo** [comment]
You need to provide some authentication to the client. You can either set `GOOGLE_APPLICATION_CREDENTIALS` or use one of the Google Cloud GitHub Actions to manage authentication: https://github.com/google-github-actions/setup-gcloud.

**Comment by sethvargo** [comment]
Hi @steve-kidreads-app - did that solve your issue?

**Comment by steve-kidreads-app** [comment]
Yes I think so.  It all makes sense but I'm still working on it. Do you think it would be worth updating your article? I'd be happy to give recommendations and/or be the clueless user guinea pig.

**Comment by sethvargo** [comment]
Yea sure - let's close this out and email me directly (sethvargo at google) and we can work together to update it.

**Comment by steve-kidreads-app** [comment]
Ok, I'm re-opening because I've run stuck and it seems like *maybe* it's a bug (but probably user error).  

Per Seth's suggestion and the documentation, I'm now trying to configure my Github Action to export the default application credentials before my Python code tries to use them.  I have this in my .yml Github Action:

```
    - name: Export GCP default credentials to get build secrets later
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true
```

I've got GCP_SERVICE_ACCOUNT_EMAIL set in my GitHub secrets and I've also set the GCP_SERVICE_ACCOUNT_KEY GitHub secret to the JSON-onput key. When I build, this step is successful:

```
Run google-github-actions/setup-gcloud@master
/usr/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/[redacted] -f /home/runner/work/_temp/[redacted]
/opt/hostedtoolcache/gcloud/330.0.0/x64/bin/gcloud --quiet auth activate-service-account *** --key-file -
Activated service account credentials for: [***]
Successfully exported Default Application Credentials
```
But when I try to call `secrets = secretmanager.SecretManagerServiceClient()` in a later step:
```
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/google/cloud/secretmanager_v1/services/secret_manager_service/client.py", line 375, in __init__
    client_info=client_info,
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/google/cloud/secretmanager_v1/services/secret_manager_service/transports/grpc.py", line 170, in __init__
    scopes=self.AUTH_SCOPES, quota_project_id=quota_project_id
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/google/auth/_default.py", line 441, in default
    credentials, project_id = checker()
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/google/auth/_default.py", line 209, in _get_explicit_environ_credentials
    os.environ[environment_vars.CREDENTIALS]
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/google/auth/_default.py", line 108, in load_credentials_from_file
    "File *** was not found.".format(filename)
google.auth.exceptions.DefaultCredentialsError: File /home/runner/work/kidreads-web/kidreads-web/[redacted] was not found.
Error: Process completed with exit code 1.
```

The line  `os.environ[environment_vars.CREDENTIALS]` indicates to me that it's looking at the env var `CREDENTIALS` instead of `GOOGLE_APPLICATION_CREDENTIALS` (where the credentials really are).  Is that accurate?  Why wouldn't auth be trying `GOOGLE_APPLICATION_CREDENTIALS`?

**Comment by sethvargo** [comment]
Can you please share your full action.yml? The error message is misleading, but it's looking at an environment variable as defined by the constant named CREDENTIALS. The string value of that constant is "GOOGLE_APPLICATION_CREDENTIALS".

**Comment by steve-kidreads-app** [comment]
Ahh, just figured it out.  I was exporting the creds *before* the step that sets up python using [actions/setup-python](https://github.com/actions/setup-python).  So actions/setup-python [creates a virtualenv](https://github.com/actions/setup-python#hosted-tool-cache) that doesn't include the `GOOGLE_APPLICATION_CREDENTIALS` that I just exported.  Doing the GCP cred export after that step fixed it.  

I had put the setup-cloud step at the very beginning because that "authenticates all future actions" according to the [get-secretmanager-secrets documentation](https://github.com/google-github-actions/get-secretmanager-secrets#via-the-setup-gcloud-action), but it looks like those docs don't account for the virtualenv.  The same might be said for the `export_default_credentials` [documentation](https://github.com/google-github-actions/setup-gcloud#inputs).

Before and after pasted below for anyone who may run across this in the future:

BEFORE (doesn't work):
```
name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Export GCP default credentials to get build secrets later
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
```

AFTER (works):
```
name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Export GCP default credentials to get build secrets later
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true
    - name: Run Tests
      run: |
        python manage.py test
```
